name: my_health_trail
description: A simple health tracking app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  csv: ^6.0.0
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
